class Autogenerated {
  List<DashboardList>? dashboardList;

  Autogenerated({this.dashboardList});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['DashboardList'] != null) {
      dashboardList = <DashboardList>[];
      json['DashboardList'].forEach((v) {
        dashboardList!.add(new DashboardList.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.dashboardList != null) {
      data['DashboardList'] =
          this.dashboardList!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class DashboardList {
  String? labelText;
  String? count;

  DashboardList({this.labelText, this.count});

  DashboardList.fromJson(Map<String, dynamic> json) {
    labelText = json['labelText'];
    count = json['Count'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['labelText'] = this.labelText;
    data['Count'] = this.count;
    return data;
  }
}
